exports.data ={
    "ReportDate": "2017-08-21T19:59:02.864534+07:00",
    "Orders": [
        {
            "Id": 216,
            "OrderId": 1560,
            "OrderDate": "2017-08-21T16:25:58",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 140.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 2.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 140.00 ,CustomerCount: 2 ,Received: 138.00",
            "Vat": 0.00,
            "GrandTotal": 138.00,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 138.00,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "11"
        },
        {
            "Id": 219,
            "OrderId": 1561,
            "OrderDate": "2017-08-21T16:49:19",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash ,VISA ,MASTER CARD ,Entertain",
            "ShiftWork": "Shift 1",
            "SubTotal": 390.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 39.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 390.00,Received: 375.57 ,CustomerCount: 2",
            "Vat": 24.57,
            "GrandTotal": 375.57,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 375.57,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        },
        {
            "Id": 220,
            "OrderId": 1562,
            "OrderDate": "2017-08-21T16:49:27",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        },
        {
            "Id": 221,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 222,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "ทดสอบภาษาไทย ฟวงสหกาฟวหก ทสฟห่กสฟา่กสฟาหก่ส ฟา่กวสฟสวสฟหากืวส ฟาืหกสฟืหกหฟาืก",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 223,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "ไก่ไก่",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 224,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 225,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 226,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 227,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 228,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 229,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 230,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 231,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 232,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 233,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 234,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 235,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 236,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 237,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 238,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 12345462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 239,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 123462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 240,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 241,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 242,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 243,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 244,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 245,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 246,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 247,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 248,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 249,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 250,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        },
        {
            "Id": 251,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 252,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 253,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 254,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 255,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 256,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 257,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 258,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 259,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 260,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 261,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 262,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 263,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 264,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 265,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 266,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 2462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 267,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 2462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 268,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 2462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 269,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Note" : "SubTotal: 480.00 ,Received: 462.24 ,CustomerCount: 2",
            "Vat": 30.24,
            "GrandTotal": 2462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
        ,
        {
            "Id": 270,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            
            "Vat": 30.24,
            "GrandTotal": 2462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
    ],
    "DeletedOrders": [],
    "DeletedGrandTotal": 0.0,
    "SummaryPaymentType": [
        {
            "Name": "Cash",
            "Amount": 1438.05,
            "Quantity": 4.0
        }
    ],
    "SubTotal": 1490.00,
    "ServiceCharge": 0.00,
    "ServiceChargeIncluded": 0.0,
    "Rounding": 0.0,
    "Discount": 137.00,
    "ItemDiscount": 0.00,
    "Vat": 85.05,
    "GrandTotal": 1438.05,
    "CardCharge": 0.0,
    "PaymentMethod": 0,
    "Received": 0.0,
    "Change": 0.0,
    "CustomerCount": 8
}
